In [99]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [100]:
df=pd.read_csv('updatedclassifier.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Unnamed: 0              4888 non-null   int64  
 1   ProdTaken               4888 non-null   int64  
 2   Age                     4888 non-null   float64
 3   TypeofContact           4888 non-null   str    
 4   CityTier                4888 non-null   int64  
 5   DurationOfPitch         4888 non-null   float64
 6   Occupation              4888 non-null   str    
 7   Gender                  4888 non-null   str    
 8   NumberOfFollowups       4888 non-null   float64
 9   ProductPitched          4888 non-null   str    
 10  PreferredPropertyStar   4888 non-null   float64
 11  MaritalStatus           4888 non-null   str    
 12  NumberOfTrips           4888 non-null   float64
 13  Passport                4888 non-null   int64  
 14  PitchSatisfactionScore  4888 non-null   int64  
 15

In [101]:
df=df.drop('Unnamed: 0', axis=1)

In [102]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0


In [103]:
x=df.drop('ProdTaken',axis=1)
y=df['ProdTaken']

In [104]:
num_feature=x.select_dtypes(exclude='str').columns
cat_feature=x.select_dtypes(include='str').columns

In [105]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
num_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

In [106]:
preprocessor=ColumnTransformer(
    [
        ("StandardScaler", num_transformer, num_feature),
        ("OneHotEncoder", cat_transformer, cat_feature)
    ]
)
x=preprocessor.fit_transform(x)

In [107]:
x

array([[ 0.3792611 ,  1.46836869, -1.12598612, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.25800887, -0.71387094, -0.16390595, ...,  1.        ,
         0.        ,  0.        ],
       [-0.06011278, -0.71387094, -0.88546608, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.58753928,  1.46836869,  0.19687412, ...,  0.        ,
         1.        ,  0.        ],
       [-2.03729526,  1.46836869,  0.0766141 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.16995625, -0.71387094, -0.16390595, ...,  0.        ,
         0.        ,  0.        ]], shape=(4888, 32))

In [108]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=42)

In [109]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,1.148165,-0.713871,-0.644946,0.289401,-0.725222,-1.223399,-0.640524,1.407276,0.782392,0.464080,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.829017,-0.713871,-0.524686,-0.712434,1.784431,1.519961,-0.640524,1.407276,-1.278132,-1.018613,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.938861,-0.713871,-0.163906,1.291235,1.784431,-0.674727,1.561221,-0.057226,0.782392,-1.224992,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,-0.938861,1.468369,-0.765206,0.289401,0.529604,-0.126055,1.561221,-0.057226,0.782392,-0.019436,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.389643,-0.713871,-0.524686,1.291235,0.529604,2.617304,-0.640524,0.675025,-1.278132,-0.429720,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,-1.048704,-0.713871,-0.644946,1.291235,-0.725222,-0.674727,-0.640524,-1.521728,0.782392,-0.539472,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3417,0.379261,1.468369,-0.885466,-0.712434,1.784431,-1.223399,-0.640524,1.407276,0.782392,1.528500,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3418,0.049731,1.468369,1.519734,0.289401,-0.725222,2.068633,-0.640524,-0.789477,0.782392,-0.362956,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3419,-1.048704,1.468369,1.760254,1.291235,-0.725222,-0.126055,-0.640524,-1.521728,0.782392,-0.255107,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0


In [110]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [111]:
models={
    "XGBoost": XGBClassifier(),
    "LogisticRegressiin": LogisticRegression(),
    "GradientBoostingClassifier":GradientBoostingClassifier(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "AdaBoostClassifier":AdaBoostClassifier(),
    "RandomForestClassifier":RandomForestClassifier()
 
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

In [112]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [113]:
print(accuracy_score(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train,y_train_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2775
           1       1.00      1.00      1.00       646

    accuracy                           1.00      3421
   macro avg       1.00      1.00      1.00      3421
weighted avg       1.00      1.00      1.00      3421

[[2775    0]
 [   0  646]]


In [114]:
print(accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test,y_test_pred))

0.9195637355146558
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      1193
           1       0.94      0.61      0.74       274

    accuracy                           0.92      1467
   macro avg       0.93      0.80      0.85      1467
weighted avg       0.92      0.92      0.91      1467

[[1183   10]
 [ 108  166]]


In [117]:
from sklearn.model_selection import RandomizedSearchCV
rf_params={
    "max_depth":[5,8,15,None, 10],
    "max_features":[3,5,8,'auto', 10],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[40,50,60,70,80,90]
    }
xgboost_param={
    "learning_rate":[0.1,0.01],
    "max_depth":[5,8,None, 10,15],
    "n-estimators":[100,200,300],
    "colsample_bytree":[0.5,0.8,1,0.3,0.4]
}
randomcv_model=[
    ("RF", RandomForestClassifier(),rf_params),
    ("XGB", XGBClassifier(),xgboost_param)
]

In [118]:
for name,model,param in randomcv_model:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=param,
                              n_iter=300,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)
    random.fit(x_train,y_train)

Fitting 3 folds for each of 300 candidates, totalling 900 fits


c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning: 
183 fits failed out of a total of 900.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
92 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\DELL\Desktop\py

Fitting 3 folds for each of 150 candidates, totalling 450 fits


In [119]:
print(accuracy_score(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train,y_train_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2775
           1       1.00      1.00      1.00       646

    accuracy                           1.00      3421
   macro avg       1.00      1.00      1.00      3421
weighted avg       1.00      1.00      1.00      3421

[[2775    0]
 [   0  646]]


In [120]:
print(accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test,y_test_pred))

0.9195637355146558
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      1193
           1       0.94      0.61      0.74       274

    accuracy                           0.92      1467
   macro avg       0.93      0.80      0.85      1467
weighted avg       0.92      0.92      0.91      1467

[[1183   10]
 [ 108  166]]
