In [1]:
import pandas as pd 
import numpy as  np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
df=pd.read_csv('Travel.csv')
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0


In [3]:
df=df.drop('CustomerID', axis=1)


In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ProdTaken                 4888 non-null   int64  
 1   Age                       4662 non-null   float64
 2   TypeofContact             4863 non-null   str    
 3   CityTier                  4888 non-null   int64  
 4   DurationOfPitch           4637 non-null   float64
 5   Occupation                4888 non-null   str    
 6   Gender                    4888 non-null   str    
 7   NumberOfPersonVisiting    4888 non-null   int64  
 8   NumberOfFollowups         4843 non-null   float64
 9   ProductPitched            4888 non-null   str    
 10  PreferredPropertyStar     4862 non-null   float64
 11  MaritalStatus             4888 non-null   str    
 12  NumberOfTrips             4748 non-null   float64
 13  Passport                  4888 non-null   int64  
 14  PitchSatisfactionSc

In [5]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df=df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ProdTaken               4888 non-null   int64  
 1   Age                     4662 non-null   float64
 2   TypeofContact           4863 non-null   str    
 3   CityTier                4888 non-null   int64  
 4   DurationOfPitch         4637 non-null   float64
 5   Occupation              4888 non-null   str    
 6   Gender                  4888 non-null   str    
 7   NumberOfFollowups       4843 non-null   float64
 8   ProductPitched          4888 non-null   str    
 9   PreferredPropertyStar   4862 non-null   float64
 10  MaritalStatus           4888 non-null   str    
 11  NumberOfTrips           4748 non-null   float64
 12  Passport                4888 non-null   int64  
 13  PitchSatisfactionScore  4888 non-null   int64  
 14  OwnCar                  4888 non-null   int64  
 15

In [6]:
df['MaritalStatus'].unique()

<ArrowStringArray>
['Single', 'Divorced', 'Married', 'Unmarried']
Length: 4, dtype: str

In [7]:
df['Gender']=df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus']=df['MaritalStatus'].replace('Single', 'Unmarried')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ProdTaken               4888 non-null   int64  
 1   Age                     4662 non-null   float64
 2   TypeofContact           4863 non-null   str    
 3   CityTier                4888 non-null   int64  
 4   DurationOfPitch         4637 non-null   float64
 5   Occupation              4888 non-null   str    
 6   Gender                  4888 non-null   str    
 7   NumberOfFollowups       4843 non-null   float64
 8   ProductPitched          4888 non-null   str    
 9   PreferredPropertyStar   4862 non-null   float64
 10  MaritalStatus           4888 non-null   str    
 11  NumberOfTrips           4748 non-null   float64
 12  Passport                4888 non-null   int64  
 13  PitchSatisfactionScore  4888 non-null   int64  
 14  OwnCar                  4888 non-null   int64  
 15

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].median())

df['TypeofContact'] = df['TypeofContact'].fillna(df['TypeofContact'].mode()[0])

df['DurationOfPitch'] = df['DurationOfPitch'].fillna(df['DurationOfPitch'].median())

df['NumberOfFollowups'] = df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mode()[0])

df['PreferredPropertyStar'] = df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0])

df['NumberOfTrips'] = df['NumberOfTrips'].fillna(df['NumberOfTrips'].median())

df['MonthlyIncome'] = df['MonthlyIncome'].fillna(df['MonthlyIncome'].median())

df['TotalVisiting'] = df['TotalVisiting'].fillna(df['TotalVisiting'].median())

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ProdTaken               4888 non-null   int64  
 1   Age                     4888 non-null   float64
 2   TypeofContact           4888 non-null   str    
 3   CityTier                4888 non-null   int64  
 4   DurationOfPitch         4888 non-null   float64
 5   Occupation              4888 non-null   str    
 6   Gender                  4888 non-null   str    
 7   NumberOfFollowups       4888 non-null   float64
 8   ProductPitched          4888 non-null   str    
 9   PreferredPropertyStar   4888 non-null   float64
 10  MaritalStatus           4888 non-null   str    
 11  NumberOfTrips           4888 non-null   float64
 12  Passport                4888 non-null   int64  
 13  PitchSatisfactionScore  4888 non-null   int64  
 14  OwnCar                  4888 non-null   int64  
 15

In [11]:
num_feature=[feature for feature in df.columns if df[feature].dtype!='str']
cat_feature=[feature for feature in df.columns if df[feature].dtype=='str']

In [12]:
discrete_feature=[feature for feature in num_feature if len(df[feature].unique())<=25]
continous_feature=[feature for feature in num_feature if feature not in discrete_feature]
df.to_csv('updatedclassifier.csv')

In [13]:
x=df.drop('ProdTaken', axis=1)
y=df['ProdTaken']

In [14]:
cat_feature=x.select_dtypes(include='str').columns
num_feature=x.select_dtypes(exclude='str').columns 

In [15]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
numeric_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [17]:
preprocessor=ColumnTransformer(
    [
        ("StandardScaler", numeric_transformer, num_feature),
        ("OneHotEncoder", cat_transformer, cat_feature)
    ]
)

In [18]:
x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

In [19]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,-0.157926,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.508072,-0.721400,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.396069,-0.721400,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.064073,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.730071,-0.721400,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,-1.045924,-0.721400,-0.653841,1.284279,-0.725271,-0.674182,-0.632399,-1.506426,0.782966,-0.536973,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3906,0.397072,1.455047,-0.898180,-0.718725,1.771041,-1.220627,-0.632399,1.408395,0.782966,1.529609,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3907,0.064073,1.455047,1.545210,0.282777,-0.725271,2.058043,-0.632399,-0.777720,0.782966,-0.360576,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3908,-1.045924,1.455047,1.789549,1.284279,-0.725271,-0.127737,-0.632399,-1.506426,0.782966,-0.252799,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0


In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import GradientBoostingClassifier

In [21]:
models={
    "AdaBoostClassifier": AdaBoostClassifier(),
    "LogisticRegression": LogisticRegression(),
    "RandomForestClassifier": RandomForestClassifier(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "GradientBoostingClassifier": GradientBoostingClassifier()
}

In [22]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train, y_train)

In [23]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [24]:
print(accuracy_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))

0.8928388746803069
[[3131   50]
 [ 369  360]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.94      3181
           1       0.88      0.49      0.63       729

    accuracy                           0.89      3910
   macro avg       0.89      0.74      0.78      3910
weighted avg       0.89      0.89      0.88      3910



In [25]:
print(accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

0.8599182004089979
[[768  19]
 [118  73]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       787
           1       0.79      0.38      0.52       191

    accuracy                           0.86       978
   macro avg       0.83      0.68      0.72       978
weighted avg       0.85      0.86      0.84       978



In [26]:
#hyperparameter Tuning
rf_param={
    "max_depth":[5,8,15,None, 10],
    "max_features":[5,7,'auto',8],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[100,200,500,1000]
}
adaboost_param={
    "n_estimators":[50,60,70,80,90],
    'learning_rate': [0.01, 0.1, 1]
}

In [27]:
from sklearn.model_selection import RandomizedSearchCV
randomcv_model=[
   ("Rg",RandomForestClassifier(),rf_param),
   ( "AB", AdaBoostClassifier(), adaboost_param)
]

In [28]:
model_param={}
for name, model, params in randomcv_model:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              n_jobs=-1
                              )
    random.fit(x_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning: 
75 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
56 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\DELL\Desktop\pyt

Fitting 3 folds for each of 15 candidates, totalling 45 fits


In [29]:
y_train_pred=random.predict(x_train)
y_test_pred=random.predict(x_test)

In [30]:
print(accuracy_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))

0.8465473145780051
[[3126   55]
 [ 545  184]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      3181
           1       0.77      0.25      0.38       729

    accuracy                           0.85      3910
   macro avg       0.81      0.62      0.65      3910
weighted avg       0.84      0.85      0.81      3910



In [31]:
print(accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

0.83640081799591
[[775  12]
 [148  43]]
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.78      0.23      0.35       191

    accuracy                           0.84       978
   macro avg       0.81      0.60      0.63       978
weighted avg       0.83      0.84      0.80       978

